# Generated by Django 5.1.7 on 2025-09-19 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='auction.item')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'time', 'price'], name='auction_sal_item_id_fb40f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'time', 'price', 'extra_data'), name='unique_sale_record')],
            },
        ),
    ]
